const jsonResponse = {
    "data": {
      "estados": [ 
        {
           "id":11,
           "sigla":"RO",
           "nome":"Rondônia",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-rondonia-105x74.png?x64851",
        },
        {
           "id":12,
           "sigla":"AC",
           "nome":"Acre",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-acre-105x74.png?x64851",	  
        },
        {
           "id":13,
           "sigla":"AM",
           "nome":"Amazonas",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-amazonas-105x75.png?x64851",	  	  
        },
        {
           "id":14,
           "sigla":"RR",
           "nome":"Roraima",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-roraima-105x74.png?x64851",	  	  
        },
        {
           "id":15,
           "sigla":"PA",
           "nome":"Pará",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-para-105x70.png?x64851",	  	  
        },
        {
           "id":16,
           "sigla":"AP",
           "nome":"Amapá",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-amapa-105x74.png?x64851",	  	  
        },
        {
           "id":17,
           "sigla":"TO",
           "nome":"Tocantins",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-tocantins-105x74.png?x64851",	  	  
        },
        {
           "id":21,
           "sigla":"MA",
           "nome":"Maranhão",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-maranhao-105x70.png?x64851",	  	  
        },
        {
           "id":22,
           "sigla":"PI",
           "nome":"Piauí",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-piaui-105x70.png?x64851",	  	  
        },
        {
           "id":23,
           "sigla":"CE",
           "nome":"Ceará",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-ceara-105x74.png?x64851",	  	  
        },
        {
           "id":24,
           "sigla":"RN",
           "nome":"Rio Grande do Norte",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-rio-grande-do-norte-105x70.png?x64851",	  	  
        },
        {
           "id":25,
           "sigla":"PB",
           "nome":"Paraíba",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-paraiba-105x74.png?x64851",	  	  
        },
        {
           "id":26,
           "sigla":"PE",
           "nome":"Pernambuco",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-pernambuco-105x74.png?x64851",	  	  
        },
        {
           "id":27,
           "sigla":"AL",
           "nome":"Alagoas",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-alagoas-105x70.png?x64851",	  	  
        },
        {
           "id":28,
           "sigla":"SE",
           "nome":"Sergipe",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-sergipe-105x74.png?x64851",	  	  
        },
        {
           "id":29,
           "sigla":"BA",
           "nome":"Bahia",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-bahia-105x70.png?x64851",	  	  
        },
        {
           "id":31,
           "sigla":"MG",
           "nome":"Minas Gerais",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-minas-gerais-105x74.png?x64851",	  	  
        },
        {
           "id":32,
           "sigla":"ES",
           "nome":"Espírito Santo",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-espirito-santo-105x74.png?x64851",	  	  
        },
        {
           "id":33,
           "sigla":"RJ",
           "nome":"Rio de Janeiro",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-rio-de-janeiro1-105x74.png?x64851",	  	  
        },
        {
           "id":35,
           "sigla":"SP",
           "nome":"São Paulo",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-sao-paulo1-105x70.png?x64851",	  	  
        },
        {
           "id":41,
           "sigla":"PR",
           "nome":"Paraná",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-parana-105x74.png?x64851",	  	  
        },
        {
           "id":42,
           "sigla":"SC",
           "nome":"Santa Catarina",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-santa-catarina-105x74.png?x64851",	  	  
        },
        {
           "id":43,
           "sigla":"RS",
           "nome":"Rio Grande do Sul",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-rio-grande-do-sul-105x74.png?x64851",	  	  
        },
        {
           "id":51,
           "sigla":"MS",
           "nome":"Mato Grosso do Sul",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-mato-grosso-do-sul-105x74.png?x64851",	  	  
        },
        {
           "id":52,
           "sigla":"MT",
           "nome":"Mato Grosso",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-mato-grosso-105x74.png?x64851",	  	  
        },
        {
           "id":53,
           "sigla":"GO",
           "nome":"Goiás",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-goias-105x75.png?x64851",	  	  
        },
        {
           "id":54,
           "sigla":"DF",
           "nome":"Distrito Federal",
            "foto":"https://www.estadosecapitaisdobrasil.com/wp-content/uploads/2014/09/bandeira-distrito-federal-105x70.png?x64851",	  	  
        }
     ]
    }
  };

export default jsonResponse;